version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - mkdir -p dist
      - cp -r out/* dist/
      - cp -r public/* dist/
      
artifacts:
  base-directory: dist
  files: '**/*'