apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: app
        image: 550829113486.dkr.ecr.sa-east-1.amazonaws.com/app-eks:latest
        ports:
        - containerPort: 80
        resources:
          requests:
             memory: "256Mi"
             cpu: "250m"
          limits:
             memory: "512Mi"
             cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80