apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80